INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'steve');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 1.00, 'steve');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.00, 'steve');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (102, 314.15, 'dashaun');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (103, 45.00, 'dashaun');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (104, 26.23, 'admin');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (105, 1.50, 'gateway-client');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (106, 2.50, 'gateway-client');
