server:
  port: 8091

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000"
          audiences:
            - "token-client"
