= Introduction

This branch of the repository contains source code for the talk _Building Modern Apps with OAuth2 and Spring_.
It is based on the workshop https://github.com/sjohnr/oauth2-workshop[Spring Security and OAuth 2.0: Step-by-Step] which was presented at SpringOne @ VMware Explore 2023.

We pick up where the workshop leaves off, and build a Spring Cloud Gateway application designed for use with a mobile app frontend.
To review content covered by the workshop this talk builds on, see the https://spring.academy[Spring Academy] course https://spring.academy/courses/spring-academy-secure-rest-api-oauth2[Securing a REST API with OAuth 2.0].

== Running the demo

The following steps can be performed to demo the end result:

First, run the applications in the following directories:

* `auth-server`
* `api`
* `mobile-client`.

Then execute the following command with HTTPie:

[source,bash]
----
http :8080/user
----

You should receive `401 Unauthorized` response.
This simulates that the mobile app is not authenticated and should proceed to the login step.

Launch the following URL in a private browser window to simulate launching a web-view or external browser on a mobile phone:

* http://127.0.0.1:8080/login

Log into the authorization server with the following credentials:

* `steve` / `password`

There is no consent screen, since we're building a 1st party client application.
You should see a blank screen with a URL like the following:

* http://127.0.0.1:8080/callback?token=12345

This simulates a callback to the mobile app with a query parameter containing a `securityContextId`, which is a generated ID for our in-memory `SecurityContext`.

[NOTE]
====
The callback location could be any URI string we wish that can call back into the mobile application.
For example, we could choose a URI registered with a particular app on the mobile OS (e.g. `myapp://callback`) or a fully qualified `https` URL (e.g. `https://myapp.com/callback`).
See https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uris-native-apps/[this article] for more info.
====

Copy the `token` parameter and export it as a variable:

[source,bash]
----
export TOKEN=...
----

Then execute the following command:

[source,bash]
----
http :8080/user "Authorization: Bearer $TOKEN"
----

You should receive the response:

[source,json]
----
{
    "username": "steve"
}
----

This simulates that the mobile app can check the authentication status using an `Authorization` header.

Execute the following commands as desired:

[source,bash]
----
http :8080/cashcards "Authorization: Bearer $TOKEN"
----

[source,bash]
----
http :8080/cashcards/1 "Authorization: Bearer $TOKEN"
----

[source,bash]
----
http POST :8080/cashcards "Authorization: Bearer $TOKEN" \
    amount=1000
----

When you're ready to log out, execute the following command:

[source,bash]
----
http POST :8080/logout "Authorization: Bearer $TOKEN"
----

You should receive a response with a `Location` header containing the OIDC client-initiated logout request.
Copy the `Location` header and paste it into a browser window to simulate launching a web-view or external browser on a mobile phone.
