INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1000, 99, 'Nike', 195.99, 'steve');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1001, 99, 'Old Navy', 52.75, 'steve');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1002, 99, 'Eddie Bauer', 152.30, 'steve');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1003, 100, 'Scooters Coffee', 6.95, 'steve');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1004, 102, 'Apple Store', 1249.99, 'cora');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1005, 102, 'Apple Store', 459.98, 'cora');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1006, 102, 'Apple Store', 999.97, 'cora');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1007, 103, 'Starbucks', 6.95, 'cora');
INSERT INTO PURCHASE(ID, CASH_CARD_ID, DESCRIPTION, AMOUNT, OWNER) VALUES (1008, 104, 'Dell', 1495.99, 'josh');
