spring:
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-name: "Log In with Spring Authorization Server"
            client-id: "oidc-client"
            client-secret: "oidc"
            provider: "spring"
            scope:
              - "openid"
              - "profile"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
          cashcard-client:
            client-name: "CashCard Client"
            client-id: "cashcard-client"
            client-secret: "cashcard"
            provider: "spring"
            scope:
              - "cashcard:read"
              - "cashcard:write"
            redirect-uri: "{baseUrl}/authorize/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
          purchase-client:
            client-name: "Purchase Client"
            client-id: "purchase-client"
            client-secret: "purchase"
            provider: "spring"
            scope:
              - "purchase:read"
            redirect-uri: "{baseUrl}/authorize/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          spring:
            issuer-uri: "http://localhost:9000"
  cloud:
    gateway:
      routes:
        - id: purchases
          uri: http://localhost:8091
          predicates:
            - Path=/cashcards/*/purchases
          filters:
            - TokenRelay=purchase-client
        - id: cashcards
          uri: http://localhost:8090
          predicates:
            - Path=/cashcards/**
          filters:
            - TokenRelay=cashcard-client
