INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (default, 123.45, 'steve');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (default, 1.00, 'steve');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (default, 150.00, 'steve');
